config/routes.rb
BiteProfile::Application.routes.draw do
  resources :products

  match "/index" => "home#index"
  
  match "/panel" => "home#panel"
  
  match "/panel/user_added" => "home#user_added"
  
  match "/panel/bite_match" => "home#bite_match"
  
  match "/panel/search" => "home#search_form"

  devise_for :users, :controllers => {:registrations => "registrations"}

  
  authenticated :user do
    root :to => 'home#panel'
  end

  root :to => "home#index"

end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  attr_accessible :allergable_id, :allergable_type, :allergen
  belongs_to :allergable, :polymorphic => true
  validates_presence_of :allergen
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :user_id, :image_url, :store_name, :allergies
  belongs_to :user
  has_many :allergies, :as => :allergable
  
  def self.distribute_in_groups(unsorted_array, number)
  sorted_array = []
  temp_array = []
    unsorted_array.each do |item|
      if temp_array.size < number
        temp_array << item
      else
        sorted_array << temp_array
        temp_array = []
        temp_array << item
      end
    end
    sorted_array << temp_array if temp_array.size > 0
    sorted_array
  end
  
  def self.search(allergens)
    if allergens
      products = []
      allergens.each do |allergen, value|
        if value.to_s == '1'
          product_found = find_by_allergen(allergen.to_s)
          products += product_found if product_found
        end
      end
      products.uniq!
      distribute_in_groups(products, 4)
    else
      distribute_in_groups(find(:all), 4)
    end
  end
  
  def self.retrieve_in_groups(batch_size)
    group_of_batches = []
    self.find_in_batches(:batch_size => batch_size) do |batch|
      group_of_batches << batch
    end
    group_of_batches
  end
  
  def self.retrieve_in_groups_for_user(user, batch_size)
    group_of_batches = []
    self.where("user_id = ?", user.id).find_in_batches(:batch_size => batch_size) do |batch|
      group_of_batches << batch
    end
    group_of_batches
  end

  def self.find_by_allergen(allergen)
    group_of_products = []
    Allergy.where("allergen = ? AND allergable_type = ?", allergen, 'Product').all.each do |allergy|
      group_of_products << allergy.allergable
    end    
    group_of_products.include?(nil) ? group_of_products.compact! : group_of_products
  end
  
  def add_allergies_from_allergens(allergens)
    if allergens != nil
      allergens.each do |allergen, value|
        if value.to_s == '1'
          Allergy.create(:allergen => allergen.to_s, :allergable_id => self.id, :allergable_type => 'Product')
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :image_url
  # attr_accessible :title, :body
  
  has_many :products
  has_many :allergies, :as => :allergable
  validates_presence_of :name
  validates_length_of :name, :minimum => 3
  validates_uniqueness_of :name, :email, :case_sensitive => false
  
  def allergic_to?(allergen)
    (find_allergy_from_allergen(self.allergies, allergen).size > 0)
  end
    
  def find_allergy_from_allergen(array, allergen)
    allergy_to_allergen_list = []
      array.each do |item|
        (allergy_to_allergen_list.push(item)) if (item.allergen == allergen)
      end
    return allergy_to_allergen_list
  end
  
  def add_allergies_from_allergens(allergens)
    if allergens != nil
      allergens.each do |allergen, value|
        if value.to_s == '1'
          Allergy.create(:allergen => allergen.to_s, :allergable_id => self.id, :allergable_type => 'User')
        end
      end
    end
  end
  
  def bite_match(number)
    matches = []
    self.allergies.each do |allergy|
      found_allergy = Product.find_by_allergen(allergy.allergen)
      (matches += found_allergy) if found_allergy != nil
    end
    distribute_in_groups(matches, number)
  end
  
  def distribute_in_groups(unsorted_array, number)
  sorted_array = []
  temp_array = []
    unsorted_array.each do |item|
      if temp_array.size < number
        temp_array << item
      else
        sorted_array << temp_array
        temp_array = []
        temp_array << item
      end
    end
    sorted_array << temp_array if temp_array.size > 0
    sorted_array
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def panel
    @products_from_bite_match = current_user.bite_match(4)
  end
  
  def bite_match
    @products_from_bite_match = current_user.bite_match(4)
  end
  
  def user_added
    @products_for_current_user = Product.retrieve_in_groups_for_user(current_user, 4)
  end
  
  def search_form
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.search(params[:allergies])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        @product.add_allergies_from_allergens(params[:allergies])
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def new
    @allergens =  [:milk, :eggs, :peanuts, :tree_nuts, :fish, :shellfish, :soy, :wheat]
    
    super
  end
  
  def create
    @allergens =  [:milk, :eggs, :peanuts, :tree_nuts, :fish, :shellfish, :soy, :wheat]
    
    build_resource
      
    if resource.save
      resource.add_allergies_from_allergens(params[:allergies])
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  Allergens =  [:milk, :eggs, :peanuts, :tree_nuts, :fish, :shellfish, :soy, :wheat]
end

app/helpers/home_helper.rb
module HomeHelper
  
  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/bite_match.html.erb
<div class="span6">
   <div id="bite-match" class="carousel slide">
   <!--  Carousel items  -->
    <div class="carousel-inner">
      <ul class="thumbnails">   
      <% @products_from_bite_match.each_with_index do |group, index| %> 
        <% if index == 0 %><!--active items-->
          <div class="active item"> 
           <% group.each do |product|%>
             <li class="span4">
               <div class="thumbnail">
               <%= link_to( image_tag(product.image_url, :alt => product.name), product) %>
               <h5><%= product.name %></h5>
               <p>Found at: <%= product.store_name %></p>
               </div>
             </li>                 
           <% end %>                 
          </div> <!--end of active item-->                    
        <% else %><!--inactive items-->
          <div class="item"> 
          <% group.each do |product|%>
            <li class="span4">
              <div class="thumbnail">
              <%= link_to( image_tag(product.image_url, :alt => product.name), product) %>
              <h5><%= product.name%></h5>
              <p>Found at: <%= product.store_name%></p>
             </div>
           </li>                
          <% end %>
          </div> <!--end of inactive items-->
        <% end %>
      <% end %>
      </ul>
     </div>
     <a class="carousel-control left" href="#bite-match" data-slide="prev">&lsaquo;</a>
     <a class="carousel-control right" href="#bite-match" data-slide="next">&rsaquo;</a>
   </div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>

  <div class="container">
      <h2 id="home-main-title">Welcome to BiteProfile</h2> 
      <div id="home-search-container">
        <h3 class="slogan">Find Products That <span>Match Your Bite!</span></h3>
        <div> <%= render :template => '/home/search_form' %> </div>
      </div>
    </div>
  
</body>
</html>

app/views/home/panel.html.erb
<div class="container-fluid" id="panel">
  <div class="tabs">
    <ul>
      <li id="tab-1" class="active"><a>Bite match</a></li>
      <li id="tab-2"><a>Added by you</a></li>
      <li id="tab-3"><a>Search</a></li>
    </ul>
  </div>
   
  <div class="row-fluid" id="panel-content"> 
    <div class="default tab">
      <%= render :template => '/home/bite_match' %>
    </div>
  </div>
    <footer>
      <p>&copy; BiteProfile 2012</p>
    </footer>
</div>

app/views/home/search_form.html.erb
<div class="span6">
  <div class="checkboxes">
    <% if !current_page?('/')%>
    <h3>Select the options that match what your bite:</h3>
    <% end %>
    <%= form_tag products_path, :method => 'get' do %>
      <%= fields_for :allergies do |allergy| %>
        <% ApplicationHelper::Allergens.each do |allergen| %>
          <div class="checkbox">
            <p>
            <%= allergy.check_box allergen %>
            <%= allergy.label (allergen.to_s + " free") %>
            </p>
          </div>
        <% end%>
      <% end %>
      <%= submit_tag "Search", :name => nil, :id => "search-submit" %>
    <% end %>
  </div>
</div>

app/views/home/user_added.html.erb
<div class="span6">
   <div id="user-added" class="carousel slide">
   <!--  Carousel items  -->
    <div class="carousel-inner">
      <ul class="thumbnails">   
      <% @products_for_current_user.each_with_index do |group, index| %>                
        <% if index == 0 %><!--active items-->
          <div class="active item"> 
           <% group.each do |product|%>
             <li class="span4">
               <div class="thumbnail">
               <%= link_to( image_tag(product.image_url, :alt => product.name), product) %>
               <h5><%= product.name %></h5>
               <p>Found at: <%= product.store_name %></p>
               </div>
             </li>                 
           <% end %>                 
          </div> <!--end of active item-->                    
        <% else %><!--inactive items-->
          <div class="item"> 
          <% group.each do |product|%>
            <li class="span4">
              <div class="thumbnail">
              <%= link_to( image_tag(product.image_url, :alt => product.name), product) %>
              <h5><%= product.name%></h5>
              <p>Found at: <%= product.store_name%></p>
             </div>
           </li>                
          <% end %>
          </div> <!--end of inactive items-->
        <% end %>
      <% end %>
      </ul>
     </div>
     <a class="carousel-control left" href="#user-added" data-slide="prev">&lsaquo;</a>
     <a class="carousel-control right" href="#user-added" data-slide="next">&rsaquo;</a>
   </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BiteProfile" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
       <div class="container">
              <div class="content">
                 <div class="row">
                  <div class="span12">
                    <%= render 'layouts/messages' %>
                    <!-- Here put anything you want to be displayed across the whole site -->
                    <% if current_page?(new_user_session_path) || 
                          current_page?(edit_user_registration_path) || 
                          current_page?(new_user_registration_path) %>
                      <h2>BiteProfile</h2>
                      <div class='form-container'>
                        <%= yield %>
                      </div>
                    <% else %>
                      <%= yield %>
                    <% end %>
                  </div>
                </div>
                <footer>
                </footer>
              </div>
            </div> <!--! end of .container -->
          </div> <!--! end of #main -->
        </body>
      </html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  
  <div class="field">
    <%= f.label :store_name %><br />
    <%= f.text_field :store_name %>
  </div>

  <div class="checkboxes">
   <h3> This product is: </h3>
   <%= fields_for :allergies do |allergy| %>
     <% ApplicationHelper::Allergens.each do |allergen| %>
     <div class="checkbox">
       <p>
        <%= allergy.check_box allergen %>
        <%= allergy.label (allergen.to_s + " free") %>
       </p>
     </div>
     <% end%>
   <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row-fluid"> 
  <div class="span6">
     <div id="user-added" class="carousel slide">
     <!--  Carousel items  -->
      <div class="carousel-inner">
        <ul class="thumbnails">   
        <% @products.each_with_index do |group, index| %>                
          <% if index == 0 %><!--active items-->
            <div class="active item"> 
             <% group.each do |product|%>
               <li class="span4">
                 <div class="thumbnail">
                 <%= link_to( image_tag(product.image_url, :alt => product.name), product) %>
                 <h5><%= product.name %></h5>
                 <p>Found at: <%= product.store_name %></p>
                 </div>
               </li>                 
             <% end %>                 
            </div> <!--end of active item-->                    
          <% else %><!--inactive items-->
            <div class="item"> 
            <% group.each do |product|%>
              <li class="span4">
                <div class="thumbnail">
                <%= link_to( image_tag(product.image_url, :alt => product.name), product) %>
                <h5><%= product.name%></h5>
                <p>Found at: <%= product.store_name%></p>
               </div>
             </li>                
            <% end %>
            </div> <!--end of inactive items-->
          <% end %>
        <% end %>
        </ul>
       </div>
       <a class="carousel-control left" href="#user-added" data-slide="prev">&lsaquo;</a>
       <a class="carousel-control right" href="#user-added" data-slide="next">&rsaquo;</a>
     </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<% if @product.allergies.size > 0 %>
  <p>
    <b>Tagged as:</b>
    <ul>
      <% @product.allergies.each do |allergy| %>
        <li><%= (allergy.allergen.capitalize + " Free") %></li>
      <% end %>
    </ul>
  </p>
<% end %>

<p>
  <b>Store:</b>
  <%= @product.store_name %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>